### ISSUE TITLE
Bulk import ALPM Database to SQlite

### ISSUE THREAD

**Issue by jelly** [anthraxx/arch-security-tracker#35]
When calling ./update we add and commit() every package, which is slower then bulk importing all the packages.

The [SQLAlchemy website](http://docs.sqlalchemy.org/en/latest/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow) has a post about bulk importing data into a database which could help us.

**Comment by anthraxx** [comment]
sounds good, as long as a writing transaction does not take longer then 10sec we are good to go.
Thanks for the link will give it a look

**Comment by anthraxx** [comment]
awesome :heart: :smirk_cat:
