### ISSUE TITLE
[todo] CVE linked to AVG or package

### ISSUE THREAD

**Issue by shibumi** [anthraxx/arch-security-tracker#4]
It would be nice to have some more columns in the **issue missing details** section.
I would really appreciate a column called **Package** or **Group**, because if you have a lot of new CVEs with unknown factors and you want to do one specific package first or look at some CVEs for a specific package you need to search all the CVEs in the OSS mail.. I would prefer a **Group** column or even better both.

**Comment by anthraxx** [comment]
well logically "do one specific package first or look at some CVEs for a specific package" is exactly what the AVG link is for: It shows all infos (like CVEs) to one specific package :smile_cat: 
It would require a left join and depending on the CVE ids it could be cluttered around in the TODO list without a particular order. I will think about it but it feels like the AVG page is the better place to get exactly what you want: It shows all issues to that group/package no matter which CVE ID it has

**Comment by shibumi** [comment]
Which AVG link do you mean? The one in **issues** or the one directly via {{ site }}/AVG-\d+ ?
I can only go to the last one if I remember the AVG number and I can only go to the first one when the AVG has no CVE with something unknown.. thats normally not the case when I want to see all CVE for a package.

At the moment we can see only AVGs with 'finished CVEs' on the **issue** page.

**Comment by anthraxx** [comment]
yep. you get redirected exactly to that page when you create a AVG so you will just need to click the CVE links. If you can't remember the AVG number then you will find it either in the issues overview or via 'open' in the packages page /pkgname.
I don't really understand what you mean by 'go to the last one' and 'go to the first one'.

"when I want to see all CVE for a package"
- http://45.32.158.89/package/php
It contains a section for all open issues to a pacakge (and another section for closed if there will be any)

**Comment by shibumi** [comment]
ahh ok I thought the issue page does only contain the AVGs in scheduling. Seems like I can see all AVGs on this page now.  But they are not sorted.

**Comment by anthraxx** [comment]
They are fully sorted. At the top unknown status vulns (to raise awareness that they are unknown and need investigation if affected) sorted by severity.  This is followed by affected groups, groups in testing and finally fixed and not affected groups all sorted per severity and date

**Comment by shibumi** [comment]
Ah ok. I thought it should be sorted by the AVG numbers. I will close this issue. I thought there are no all AVGs in the issue list. But seems like I was wrong.
