### ISSUE TITLE
RSS feed for advisories

### ISSUE THREAD

**Issue by DragoonAethis** [anthraxx/arch-security-tracker#41]
Initially posted here (before I've found the project on GitHub): https://bugs.archlinux.org/task/52218

RSS feed for advisories would be greatly appreciated for automated notifications.

**Comment by anthraxx** [comment]
@DragoonAethis sure, why not. can we close the one on the archlinux tracker?

**Comment by DragoonAethis** [comment]
Yep, no problem.

**Comment by jelly** [comment]
Seems werkzeug has an atomfeed lib http://werkzeug.pocoo.org/docs/0.11/contrib/atom/

**Comment by anthraxx** [comment]
thanks to @jelly we have this ready, will be available after next deployment via /advisory/feed.atom

**Comment by eli-schwartz** [comment]
I cannot seem to find anywhere this feed is advertised.

(I also thought it was common practice to take an url, e.g. https://security.archlinux.org/advisory and append .atom to make a feed, not append /feed.atom -- so eve testing random hopeful urls is not necessarily going to find the existing feed.)

**Comment by evaryont** [comment]
I don't see a link to the Atom feed in the body of the document, but it is properly advertised to clients in a machine friendly fashion already, and has been for months. The atom feed for advisories has the appropriate `<link>` tag so browsers and other HTTP clients can react appropriately. (For instance, Firefox's feed button will light up on the page indicating the presence of a RSS or Atom feed. If you're using Chrome, there may be an extension that suits you.)

**Comment by jelly** [comment]
Ah yeah it's documented [here](https://developer.mozilla.org/en-US/docs/Web/RSS/Getting_Started/Syndicating), I think we can add a <link> to the body of the relevant pages. But there should also be an RSS icon somewhere on the page itself.

**Comment by anthraxx** [comment]
Machines can already read the <link> tag: view-source:https://security.archlinux.org/advisory
