### ISSUE TITLE
Add Arch Linux Header Links

### ISSUE THREAD

**Issue by shibumi** [anthraxx/arch-security-tracker#43]
It would be nice to have all possible Links in the header on security.archlinux.org:

Example for wiki.archlinux.org:

![](https://paste.archlinux.de/hsx/)

We should make sure to have these Links on the other archlinux subpages also.

**Comment by anthraxx** [comment]
We need to clarify at which position "Security" should be (maybe before download)? This has to be made on a higher level as it also affects AUR, archweb and other header providers

**Comment by anthraxx** [comment]
fixed via cd875f6ffc6b7817ad984c04e5b662d539089e43
