### ISSUE TITLE
[feature request] bugreport generator

### ISSUE THREAD

**Issue by shibumi** [anthraxx/arch-security-tracker#6]
It would be nice to have a form for generating bugreports. 
This way all bugreports from us would have the same structure.

**Comment by anthraxx** [comment]
we should have a button/page to automate the creation of a standardized bug report to our tracker including a back reference to the security trackers AVG link for the package maintainers.

**Comment by jelly** [comment]
Our bugreport template is located here: https://wiki.archlinux.org/index.php/Security_Advisories/Examples

ArchWeb uses this simple code, to generate an bugreport url
```
def bug_report(package):
    url = "https://bugs.archlinux.org/newtask"
    data = {
        'project': package.repo.bugs_project,
        'product_category': package.repo.bugs_category,
        'item_summary': '[%s] PLEASE ENTER SUMMARY' % package.pkgname,
    }
    return link_encode(url, data)
```

https://bugs.archlinux.org/newtask?project=1&product_category=10&item_summary=%5Blinux%5D+PLEASE+ENTER+SUMMARY&detailed_desc=the%20bug%20description
