### ISSUE TITLE
[license] We still need a LICENSE :)

### ISSUE THREAD

**Issue by shibumi** [anthraxx/arch-security-tracker#7]
We must have a license when we want to use it official.

**Comment by SantiagoTorres** [comment]
what about [beerware](https://en.wikipedia.org/wiki/Beerware) ?

**Comment by shibumi** [comment]
I think @anthraxx thought about MIT. It's his software. He shall decide :)

**Comment by anthraxx** [comment]
fixed in 9ff0505fe40fb2b3c838522c3ba78ab604e02cd0
